# Generated by Django 2.0.6 on 2018-06-12 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='tag',
            new_name='tags',
        ),
    ]
